name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: backend
      FRONTEND_DIR: frontend
      BACKEND_DEPLOY_PATH: /srv/api-test
      FRONTEND_DEPLOY_PATH: /var/www/intellect37.com/api-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build backend
      run: |
        cd ${{ env.BACKEND_DIR }}
        mvn clean package -DskipTests

    - name: Deploy backend
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key
        scp -i ssh_key ${{ env.BACKEND_DIR }}/target/*.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ env.BACKEND_DEPLOY_PATH }}/api-test.jar
        ssh -i ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo systemctl restart api-test.service"
        rm -f ssh_key

    - name: Deploy frontend
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key
        rsync -e "ssh -i ssh_key" -avz ${{ env.FRONTEND_DIR }}/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ env.FRONTEND_DEPLOY_PATH }}
        rm -f ssh_key
