name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: backend
      FRONTEND_DIR: frontend/public
      BACKEND_DEPLOY_PATH: /srv/api-test
      FRONTEND_DEPLOY_PATH: /var/www/intellect37.com/api-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build backend
      run: |
        cd ${{ env.BACKEND_DIR }}
        mvn clean package -DskipTests

    - name: Add server to known_hosts
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: Setup SSH Key
      env:
        SERVER_SSH_KEY_BASE64: ${{ secrets.SERVER_SSH_KEY_BASE64 }}
      run: |
        echo "${{ secrets.SERVER_SSH_KEY_BASE64 }}" | base64 -d > ssh_key
        chmod 600 ssh_key
        eval $(ssh-agent -s)
        ssh-add ssh_key
        ssh-add -l  # List the added keys for debugging

    - name: Deploy backend
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        scp -i ssh_key ${{ env.BACKEND_DIR }}/target/*.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ env.BACKEND_DEPLOY_PATH }}/api-test.jar
        ssh -i ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo systemctl restart api-test.service"

    - name: Deploy frontend
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        rsync -e "ssh -i ssh_key" -avz ${{ env.FRONTEND_DIR }}/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ env.FRONTEND_DEPLOY_PATH }}

    - name: Cleanup
      run: |
        ssh-agent -k  # Kill the ssh-agent
        rm -f ssh_key
